mkdocs-material Docker image based on binary
afritzler/mkdocs-material pull request #33
Opened 2021-12-22 10:58 UTC by SchulteMarkus

Original mkdocs-material Docker image is using mkdocs the "classic" way by executing Python.
This docker image encapsulates mkdocs as a binary.

Follow up of https://github.com/squidfunk/mkdocs-material/pull/3375

2021-12-22 11:05 UTC, SchulteMarkus commented
While in my opinion this PR itself is worth merging, I think there are questions raising up afterwards in the scope of project organization.

What comes to my mind:
- [ ] How to organize this repo, maybe rename it?
- [ ] What about rebuilding and testing
- [ ] How to keep releases in sync with mkdocs-material
- [ ] Some additional documentation is being required, maybe use mkdocs-material itself? I will participate in documentation for the binary once we know the format.

Further improvement: Once we have organized ourself I would like to add one more binary build for Windows.

2021-12-22 13:09 UTC, afritzler commented
Thanks for the PR! You are covering a lot of ground with your questions so let me go over some of the points:

**Keeping things up to date**
The current approach is using a `requirements.txt` (+ a separate one for the plugins) and the doing vanilla packaging via `pip`. Dependabot is doing the upgrade PRs as soon as @squidfunk is creating a new release. I try to keep here the versions in sync with the upstream project.

I am not sure if moving the original Dockerfile to this project is a good idea because @squidfunk is using it for his workflow.

**Test builds for PRs**
You are right on that one. The Github action should do a test build of the container image to see if everything works as expected. I will open an issue for that one.

**Documentation**
The documentation can always be improved. I just wanted to keep it to a minimum as I rely on ppl going to the official documentation of the project which is outstanding.

**Other open points**
Renaming or multi platforming support: the intention of this project was to provide a Docker based local setup environment for ARM base systems. We are actually using this in our team setup and some of the ppl on our team have an M1 based local dev setup. So I would really like to keep it that way.

As for Windows support and/or binary release artefacts: I would suggest to create an own repository for that. Since I don't have a Windows machine at hand I can only test Linux/Darwin based setups from my side.

2021-12-22 13:15 UTC, afritzler requested changes
I would suggest to rename the Dockerfile to `Dockerfile.minimal` or `Dockerfile.pyinstaller`.

2021-12-22 13:15 UTC, afritzler commented on Dockerfile_binary-linux-amd64
> +FROM alpine
I would suggest to use a tagged version here. Dependabot will do the upgrade. That way we can guaranty the reproducibility of our builds.

2021-12-22 13:15 UTC, afritzler commented on Dockerfile_binary-linux-amd64
> +RUN ln -s /opt/mkdocs-material/mkdocs-material /usr/local/bin/mkdocs
Why not just straight copy the output to `/usr/local/bin/mkdocs`

2021-12-22 13:15 UTC, afritzler commented on Dockerfile_binary-linux-amd64
> +FROM squidfunk/mkdocs-material:8.1.3 as source
I would suggest to use the same from scratch build as in the main `Dockerfile`.

2021-12-22 13:23 UTC, SchulteMarkus commented
> **Other open points** Renaming or multi platforming support: the intention of this project was to provide a Docker based local setup environment for ARM base systems. We are actually using this in our team setup and some of the ppl on our team have an M1 based local dev setup. So I would really like to keep it that way.

I have seen your other comments - this one seems to be a critical one.
I think if this repository cannot be reorganized, it won't be a good choice for being "mkdocs-material exotic (Docker) builds". So there is no option of reshaping? In this case, I would open an own repo.

2021-12-22 16:59 UTC, squidfunk commented
I don't intend to move the `Dockerfile` out of the main repository because I'm also pushing a Docker image on every release. Breaking co-location will make the original Docker builds either unpredictable or we need to pin versions and upgrade deliberately. Either way, more work for me. This repository here exists because we need a canonical way to build a Docker image that can be used for extension and which solves 80-90% of cases, and everything else should be done by third parties.

As said, I'm happy to add stuff to the documentation if it provides value. I'm still unsure if a `PyInstaller` based Docker image adds value though, because, yes, it is smaller, but users will definitely try to install plugins, which will not work. IMHO, layer caching is the way to go, if supported. If 6 years of Material for MkDocs taught me one thing, it's that you should make your software as simple and predictable as possible, especially if its consumed downstream.

Everything that can happen will happen.

2021-12-22 17:03 UTC, squidfunk commented
On a further note: the Docker image is only used by a fraction of users. It has seen __3.3M pulls in 5 years__, whereas the Python package currently has __750k every month__.

2021-12-23 16:16 UTC, SchulteMarkus commented
Sooo I'm giving up on this one.
I'm kind of in love with the idea of having a standalone binary somewhere available (neither Python nor Docker required - as @afritzler says, knowing this from Golang changes the world a bit). 
But building and maintaining won't be fun, it has the big disadvantage of no (easy) additional MkDocs plugins, and probably no one needs it.

2021-12-23 16:16 UTC, closed without merging

2022-01-07 14:58 UTC, afritzler commented
Sorry for the delayed response here. Holiday season just ended for me. :)

How about creating a single binary release repository containing the binary artifacts for the various platforms. You could use something similar to https://github.com/goreleaser/goreleaser-action to generate the corresponding release artifacts. 

I would suggest to try this out and see how that goes and if somebody would actually use that e.g. under Windows - once that happens I would start thinking about the next steps.

The thing is: for most people (including me) the local setup via Docker image works just fine and here you don't really care if it is a single binary distribution inside the container or full fledged Python setup.

As I am professionally (and hobby wise) responsible for a lot of Github projects I want to keep the maintenance effort as low as possible.

Just my 2 cents ...